//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAIFMVC.EAIFDataServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EAIFMVC.EAIFDataServiceReference.CompanyCategory CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EAIFMVC.EAIFDataServiceReference.DangerCategory DangerCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LawPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StorageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contactorNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EAIFMVC.EAIFDataServiceReference.CompanyCategory Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactorID {
            get {
                return this.ContactorIDField;
            }
            set {
                if ((this.ContactorIDField.Equals(value) != true)) {
                    this.ContactorIDField = value;
                    this.RaisePropertyChanged("ContactorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EAIFMVC.EAIFDataServiceReference.DangerCategory DangerCategory {
            get {
                return this.DangerCategoryField;
            }
            set {
                if ((this.DangerCategoryField.Equals(value) != true)) {
                    this.DangerCategoryField = value;
                    this.RaisePropertyChanged("DangerCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LawPerson {
            get {
                return this.LawPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.LawPersonField, value) != true)) {
                    this.LawPersonField = value;
                    this.RaisePropertyChanged("LawPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Storage {
            get {
                return this.StorageField;
            }
            set {
                if ((this.StorageField.Equals(value) != true)) {
                    this.StorageField = value;
                    this.RaisePropertyChanged("Storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contactorName {
            get {
                return this.contactorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.contactorNameField, value) != true)) {
                    this.contactorNameField = value;
                    this.RaisePropertyChanged("contactorName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompanyCategory", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    public enum CompanyCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Type1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Type2 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DangerCategory", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    public enum DangerCategory : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cat1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cat2 = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alert", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    [System.SerializableAttribute()]
    public partial class Alert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AlertTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DangerSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EAIFMVC.EAIFDataServiceReference.AlertStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AlertTime {
            get {
                return this.AlertTimeField;
            }
            set {
                if ((this.AlertTimeField.Equals(value) != true)) {
                    this.AlertTimeField = value;
                    this.RaisePropertyChanged("AlertTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DangerSource {
            get {
                return this.DangerSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.DangerSourceField, value) != true)) {
                    this.DangerSourceField = value;
                    this.RaisePropertyChanged("DangerSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EAIFMVC.EAIFDataServiceReference.AlertStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlertStatus", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    public enum AlertStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unhandled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incorrect = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contactor", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    [System.SerializableAttribute()]
    public partial class Contactor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EAIFMVC.EAIFDataServiceReference.NotficationStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EAIFMVC.EAIFDataServiceReference.NotificationType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EAIFMVC.EAIFDataServiceReference.NotficationStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EAIFMVC.EAIFDataServiceReference.NotificationType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotficationStatus", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    public enum NotficationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnRead = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationType", Namespace="http://schemas.datacontract.org/2004/07/EAIFStorageService.Service")]
    public enum NotificationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alert = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceBug = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EAIFDataServiceReference.IEAIFDataService")]
    public interface IEAIFDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadCompany", ReplyAction="http://tempuri.org/IEAIFDataService/LoadCompanyResponse")]
        EAIFMVC.EAIFDataServiceReference.LoadCompanyResponse LoadCompany(EAIFMVC.EAIFDataServiceReference.LoadCompanyRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadCompany", ReplyAction="http://tempuri.org/IEAIFDataService/LoadCompanyResponse")]
        System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadCompanyResponse> LoadCompanyAsync(EAIFMVC.EAIFDataServiceReference.LoadCompanyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadCompanyList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadCompanyListResponse")]
        EAIFMVC.EAIFDataServiceReference.LoadCompanyListResponse LoadCompanyList(EAIFMVC.EAIFDataServiceReference.LoadCompanyListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadCompanyList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadCompanyListResponse")]
        System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadCompanyListResponse> LoadCompanyListAsync(EAIFMVC.EAIFDataServiceReference.LoadCompanyListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadAlert", ReplyAction="http://tempuri.org/IEAIFDataService/LoadAlertResponse")]
        EAIFMVC.EAIFDataServiceReference.LoadAlertResponse LoadAlert(EAIFMVC.EAIFDataServiceReference.LoadAlertRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadAlert", ReplyAction="http://tempuri.org/IEAIFDataService/LoadAlertResponse")]
        System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadAlertResponse> LoadAlertAsync(EAIFMVC.EAIFDataServiceReference.LoadAlertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadAlertList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadAlertListResponse")]
        EAIFMVC.EAIFDataServiceReference.LoadAlertListResponse LoadAlertList(EAIFMVC.EAIFDataServiceReference.LoadAlertListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadAlertList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadAlertListResponse")]
        System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadAlertListResponse> LoadAlertListAsync(EAIFMVC.EAIFDataServiceReference.LoadAlertListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/SearchAlerts", ReplyAction="http://tempuri.org/IEAIFDataService/SearchAlertsResponse")]
        EAIFMVC.EAIFDataServiceReference.SearchAlertsResponse SearchAlerts(EAIFMVC.EAIFDataServiceReference.SearchAlertsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/SearchAlerts", ReplyAction="http://tempuri.org/IEAIFDataService/SearchAlertsResponse")]
        System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.SearchAlertsResponse> SearchAlertsAsync(EAIFMVC.EAIFDataServiceReference.SearchAlertsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadContactorList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadContactorListResponse")]
        EAIFMVC.EAIFDataServiceReference.LoadContactorListResponse LoadContactorList(EAIFMVC.EAIFDataServiceReference.LoadContactorListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadContactorList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadContactorListResponse")]
        System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadContactorListResponse> LoadContactorListAsync(EAIFMVC.EAIFDataServiceReference.LoadContactorListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadNotificationList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadNotificationListResponse")]
        EAIFMVC.EAIFDataServiceReference.LoadNotificationListResponse LoadNotificationList(EAIFMVC.EAIFDataServiceReference.LoadNotificationListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEAIFDataService/LoadNotificationList", ReplyAction="http://tempuri.org/IEAIFDataService/LoadNotificationListResponse")]
        System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadNotificationListResponse> LoadNotificationListAsync(EAIFMVC.EAIFDataServiceReference.LoadNotificationListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadCompany", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadCompanyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid id;
        
        public LoadCompanyRequest() {
        }
        
        public LoadCompanyRequest(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadCompanyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadCompanyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EAIFMVC.EAIFDataServiceReference.Company LoadCompanyResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public LoadCompanyResponse() {
        }
        
        public LoadCompanyResponse(EAIFMVC.EAIFDataServiceReference.Company LoadCompanyResult, string errorMessage) {
            this.LoadCompanyResult = LoadCompanyResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadCompanyList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadCompanyListRequest {
        
        public LoadCompanyListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadCompanyListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadCompanyListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EAIFMVC.EAIFDataServiceReference.Company[] LoadCompanyListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public LoadCompanyListResponse() {
        }
        
        public LoadCompanyListResponse(EAIFMVC.EAIFDataServiceReference.Company[] LoadCompanyListResult, string errorMessage) {
            this.LoadCompanyListResult = LoadCompanyListResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAlert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadAlertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid id;
        
        public LoadAlertRequest() {
        }
        
        public LoadAlertRequest(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAlertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadAlertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EAIFMVC.EAIFDataServiceReference.Alert LoadAlertResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public LoadAlertResponse() {
        }
        
        public LoadAlertResponse(EAIFMVC.EAIFDataServiceReference.Alert LoadAlertResult, string errorMessage) {
            this.LoadAlertResult = LoadAlertResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAlertList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadAlertListRequest {
        
        public LoadAlertListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAlertListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadAlertListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EAIFMVC.EAIFDataServiceReference.Alert[] LoadAlertListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public LoadAlertListResponse() {
        }
        
        public LoadAlertListResponse(EAIFMVC.EAIFDataServiceReference.Alert[] LoadAlertListResult, string errorMessage) {
            this.LoadAlertListResult = LoadAlertListResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAlerts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchAlertsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Nullable<System.DateTime> startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Nullable<System.DateTime> endTime;
        
        public SearchAlertsRequest() {
        }
        
        public SearchAlertsRequest(System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime) {
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchAlertsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SearchAlertsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EAIFMVC.EAIFDataServiceReference.Alert[] SearchAlertsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public SearchAlertsResponse() {
        }
        
        public SearchAlertsResponse(EAIFMVC.EAIFDataServiceReference.Alert[] SearchAlertsResult, string errorMessage) {
            this.SearchAlertsResult = SearchAlertsResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadContactorList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadContactorListRequest {
        
        public LoadContactorListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadContactorListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadContactorListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EAIFMVC.EAIFDataServiceReference.Contactor[] LoadContactorListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public LoadContactorListResponse() {
        }
        
        public LoadContactorListResponse(EAIFMVC.EAIFDataServiceReference.Contactor[] LoadContactorListResult, string errorMessage) {
            this.LoadContactorListResult = LoadContactorListResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadNotificationList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadNotificationListRequest {
        
        public LoadNotificationListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadNotificationListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadNotificationListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EAIFMVC.EAIFDataServiceReference.Notification[] LoadNotificationListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorMessage;
        
        public LoadNotificationListResponse() {
        }
        
        public LoadNotificationListResponse(EAIFMVC.EAIFDataServiceReference.Notification[] LoadNotificationListResult, string errorMessage) {
            this.LoadNotificationListResult = LoadNotificationListResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEAIFDataServiceChannel : EAIFMVC.EAIFDataServiceReference.IEAIFDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EAIFDataServiceClient : System.ServiceModel.ClientBase<EAIFMVC.EAIFDataServiceReference.IEAIFDataService>, EAIFMVC.EAIFDataServiceReference.IEAIFDataService {
        
        public EAIFDataServiceClient() {
        }
        
        public EAIFDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EAIFDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAIFDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EAIFDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EAIFMVC.EAIFDataServiceReference.LoadCompanyResponse EAIFMVC.EAIFDataServiceReference.IEAIFDataService.LoadCompany(EAIFMVC.EAIFDataServiceReference.LoadCompanyRequest request) {
            return base.Channel.LoadCompany(request);
        }
        
        public EAIFMVC.EAIFDataServiceReference.Company LoadCompany(System.Guid id, out string errorMessage) {
            EAIFMVC.EAIFDataServiceReference.LoadCompanyRequest inValue = new EAIFMVC.EAIFDataServiceReference.LoadCompanyRequest();
            inValue.id = id;
            EAIFMVC.EAIFDataServiceReference.LoadCompanyResponse retVal = ((EAIFMVC.EAIFDataServiceReference.IEAIFDataService)(this)).LoadCompany(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.LoadCompanyResult;
        }
        
        public System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadCompanyResponse> LoadCompanyAsync(EAIFMVC.EAIFDataServiceReference.LoadCompanyRequest request) {
            return base.Channel.LoadCompanyAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EAIFMVC.EAIFDataServiceReference.LoadCompanyListResponse EAIFMVC.EAIFDataServiceReference.IEAIFDataService.LoadCompanyList(EAIFMVC.EAIFDataServiceReference.LoadCompanyListRequest request) {
            return base.Channel.LoadCompanyList(request);
        }
        
        public EAIFMVC.EAIFDataServiceReference.Company[] LoadCompanyList(out string errorMessage) {
            EAIFMVC.EAIFDataServiceReference.LoadCompanyListRequest inValue = new EAIFMVC.EAIFDataServiceReference.LoadCompanyListRequest();
            EAIFMVC.EAIFDataServiceReference.LoadCompanyListResponse retVal = ((EAIFMVC.EAIFDataServiceReference.IEAIFDataService)(this)).LoadCompanyList(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.LoadCompanyListResult;
        }
        
        public System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadCompanyListResponse> LoadCompanyListAsync(EAIFMVC.EAIFDataServiceReference.LoadCompanyListRequest request) {
            return base.Channel.LoadCompanyListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EAIFMVC.EAIFDataServiceReference.LoadAlertResponse EAIFMVC.EAIFDataServiceReference.IEAIFDataService.LoadAlert(EAIFMVC.EAIFDataServiceReference.LoadAlertRequest request) {
            return base.Channel.LoadAlert(request);
        }
        
        public EAIFMVC.EAIFDataServiceReference.Alert LoadAlert(System.Guid id, out string errorMessage) {
            EAIFMVC.EAIFDataServiceReference.LoadAlertRequest inValue = new EAIFMVC.EAIFDataServiceReference.LoadAlertRequest();
            inValue.id = id;
            EAIFMVC.EAIFDataServiceReference.LoadAlertResponse retVal = ((EAIFMVC.EAIFDataServiceReference.IEAIFDataService)(this)).LoadAlert(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.LoadAlertResult;
        }
        
        public System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadAlertResponse> LoadAlertAsync(EAIFMVC.EAIFDataServiceReference.LoadAlertRequest request) {
            return base.Channel.LoadAlertAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EAIFMVC.EAIFDataServiceReference.LoadAlertListResponse EAIFMVC.EAIFDataServiceReference.IEAIFDataService.LoadAlertList(EAIFMVC.EAIFDataServiceReference.LoadAlertListRequest request) {
            return base.Channel.LoadAlertList(request);
        }
        
        public EAIFMVC.EAIFDataServiceReference.Alert[] LoadAlertList(out string errorMessage) {
            EAIFMVC.EAIFDataServiceReference.LoadAlertListRequest inValue = new EAIFMVC.EAIFDataServiceReference.LoadAlertListRequest();
            EAIFMVC.EAIFDataServiceReference.LoadAlertListResponse retVal = ((EAIFMVC.EAIFDataServiceReference.IEAIFDataService)(this)).LoadAlertList(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.LoadAlertListResult;
        }
        
        public System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadAlertListResponse> LoadAlertListAsync(EAIFMVC.EAIFDataServiceReference.LoadAlertListRequest request) {
            return base.Channel.LoadAlertListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EAIFMVC.EAIFDataServiceReference.SearchAlertsResponse EAIFMVC.EAIFDataServiceReference.IEAIFDataService.SearchAlerts(EAIFMVC.EAIFDataServiceReference.SearchAlertsRequest request) {
            return base.Channel.SearchAlerts(request);
        }
        
        public EAIFMVC.EAIFDataServiceReference.Alert[] SearchAlerts(System.Nullable<System.DateTime> startTime, System.Nullable<System.DateTime> endTime, out string errorMessage) {
            EAIFMVC.EAIFDataServiceReference.SearchAlertsRequest inValue = new EAIFMVC.EAIFDataServiceReference.SearchAlertsRequest();
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            EAIFMVC.EAIFDataServiceReference.SearchAlertsResponse retVal = ((EAIFMVC.EAIFDataServiceReference.IEAIFDataService)(this)).SearchAlerts(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.SearchAlertsResult;
        }
        
        public System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.SearchAlertsResponse> SearchAlertsAsync(EAIFMVC.EAIFDataServiceReference.SearchAlertsRequest request) {
            return base.Channel.SearchAlertsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EAIFMVC.EAIFDataServiceReference.LoadContactorListResponse EAIFMVC.EAIFDataServiceReference.IEAIFDataService.LoadContactorList(EAIFMVC.EAIFDataServiceReference.LoadContactorListRequest request) {
            return base.Channel.LoadContactorList(request);
        }
        
        public EAIFMVC.EAIFDataServiceReference.Contactor[] LoadContactorList(out string errorMessage) {
            EAIFMVC.EAIFDataServiceReference.LoadContactorListRequest inValue = new EAIFMVC.EAIFDataServiceReference.LoadContactorListRequest();
            EAIFMVC.EAIFDataServiceReference.LoadContactorListResponse retVal = ((EAIFMVC.EAIFDataServiceReference.IEAIFDataService)(this)).LoadContactorList(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.LoadContactorListResult;
        }
        
        public System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadContactorListResponse> LoadContactorListAsync(EAIFMVC.EAIFDataServiceReference.LoadContactorListRequest request) {
            return base.Channel.LoadContactorListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EAIFMVC.EAIFDataServiceReference.LoadNotificationListResponse EAIFMVC.EAIFDataServiceReference.IEAIFDataService.LoadNotificationList(EAIFMVC.EAIFDataServiceReference.LoadNotificationListRequest request) {
            return base.Channel.LoadNotificationList(request);
        }
        
        public EAIFMVC.EAIFDataServiceReference.Notification[] LoadNotificationList(out string errorMessage) {
            EAIFMVC.EAIFDataServiceReference.LoadNotificationListRequest inValue = new EAIFMVC.EAIFDataServiceReference.LoadNotificationListRequest();
            EAIFMVC.EAIFDataServiceReference.LoadNotificationListResponse retVal = ((EAIFMVC.EAIFDataServiceReference.IEAIFDataService)(this)).LoadNotificationList(inValue);
            errorMessage = retVal.errorMessage;
            return retVal.LoadNotificationListResult;
        }
        
        public System.Threading.Tasks.Task<EAIFMVC.EAIFDataServiceReference.LoadNotificationListResponse> LoadNotificationListAsync(EAIFMVC.EAIFDataServiceReference.LoadNotificationListRequest request) {
            return base.Channel.LoadNotificationListAsync(request);
        }
    }
}
